### ISSUE TITLE
Post-release roadmap

### ISSUE THREAD

**Issue by camdendotlol** [camdendotlol/topstersorg#4]
Now that it's officially released, it's time to plan what the road ahead is like.

These should all be pretty simple:

- [x] add a toggle for drop-shadows in chart (very important for making it usable on Firefox, which lags badly with Canvas drop shadows)
- [x] custom fonts
- [x] custom text color
- [ ] last.fm import
- [ ] customizable margin along the edges of the chart, separate from the gap setting

Stretch goals that would require more work and/or a lot of refactoring:

- [ ] support for different layouts beyond the grid, including the traditional descending-size charts and some new ones
- [ ] ability to save a chart server-side and share it with friends via link

**Comment by mythmakerseven** [comment]
I've been thinking about an alternate covers feature. OpenLibrary and Last.fm both provide alternate artwork through their APIs. This is especially useful for OpenLibrary which often has strange choices for the cover edition.

It would probably be a small button on the bottom right of a result item, with an "arrow repeat" Bootstrap icon. This would open a small modal with a list of the different covers. The covers should behave the same as the results pane, i.e. clicking or dragging should add them to the chart.

**Comment by camdendotlol** [comment]
Closing in favor of individual issues.
